---
version: '3.5'

networks:
    portal:
        name: kalaxia_portal
        driver: bridge

services:
    app:
        container_name: portal_app
        build: .
        working_dir: /srv/app
        env_file:
            - portal.env
        networks:
            - portal
        volumes:
            - "./:/srv/app"

    bot:
        container_name: discord_bot
        image: kalaxia/discord-bot
        env_file:
            - portal.env
        networks:
            - portal

    nginx:
        container_name: portal_nginx
        build: build/docker/nginx
        depends_on:
            - app
        env_file:
            - portal.env
        volumes:
            - "./:/srv/app"
            - "./var/ssl:/etc/ssl"
            - "./var/log:/var/log/nginx"
        networks:
            - portal
        ports:
            - 443:443
            - 80:80

    mysql:
        container_name: portal_mysql
        image: mysql:5.7
        env_file:
            - portal.env
        networks:
            - portal
        volumes:
            - "./var/data:/var/lib/mysql"